"""
app/agents/state.py
ResearchState TypedDict — the single shared state object
passed through every node in the LangGraph pipeline.
"""

from typing import Annotated, Any, Optional
import operator
from typing_extensions import TypedDict


class SourceDoc(TypedDict):
    """A retrieved source document from any data source."""
    title: str
    url: str
    content: str
    source_type: str       # arxiv | wikipedia | news | web | user_doc
    confidence: float      # 0.0 – 1.0 credibility score
    published_date: str    # ISO date string or empty


class Contradiction(TypedDict):
    """A detected contradiction between two sources."""
    claim: str
    source_a: str
    source_b: str
    detail: str
    severity: str          # low | medium | high


class FactCheckResult(TypedDict):
    """Fact-check verdict for a single claim."""
    claim: str
    verdict: str           # verified | disputed | unverified
    confidence: float
    evidence: str


class Hypothesis(TypedDict):
    """A generated research hypothesis with reasoning chain."""
    text: str
    reasoning_chain: list[str]
    confidence: float


class Citation(TypedDict):
    """A formatted citation for the report."""
    index: int
    title: str
    url: str
    source_type: str
    authors: str
    published_date: str


class QualityScore(TypedDict):
    """LLM-as-a-Judge quality evaluation."""
    overall_score: float   # 0.0 – 10.0
    clarity: float
    depth: float
    accuracy: float
    completeness: float
    feedback: str
    passed: bool           # True if score >= threshold


class AgentEvent(TypedDict):
    """A streaming event emitted by an agent node."""
    agent: str
    action: str
    message: str
    timestamp: str


class ResearchState(TypedDict):
    """
    Complete shared state for the multi-agent research pipeline.

    Fields marked with Annotated[list, operator.add] support parallel
    fan-out — multiple agents can append to them concurrently.
    """

    # ── Input ─────────────────────────────────────────────────
    query: str                          # Original user query
    depth: str                          # quick | deep | expert
    session_id: str                     # Unique session identifier
    user_id: str                        # Authenticated user ID from Clerk

    # ── Planner output ────────────────────────────────────────
    research_plan: list[str]            # Sub-questions generated by planner
    agent_tasks: dict[str, list[str]]   # Task assignments per agent

    # ── Retrieved documents ───────────────────────────────────
    sources: Annotated[list[SourceDoc], operator.add]
    raw_texts: Annotated[list[str], operator.add]

    # ── Analysis outputs ─────────────────────────────────────
    summaries: Annotated[list[str], operator.add]
    contradictions: Annotated[list[Contradiction], operator.add]

    # ── Insight outputs ───────────────────────────────────────
    hypotheses: Annotated[list[Hypothesis], operator.add]
    trends: Annotated[list[str], operator.add]

    # ── Fact-check & citation ─────────────────────────────────
    fact_checks: Annotated[list[FactCheckResult], operator.add]
    citations: Annotated[list[Citation], operator.add]

    # ── Final report ─────────────────────────────────────────
    report: Optional[dict[str, Any]]   # Structured report object

    # ── Quality / self-correction ─────────────────────────────
    quality_score: Optional[QualityScore]
    correction_loop_count: int         # How many self-correction loops ran
    needs_correction: bool             # Judge says re-analyse?

    # ── HITL (Human-in-the-Loop) ──────────────────────────────
    hitl_approved: bool                # Human approved the draft report?
    hitl_feedback: str                 # Human reviewer's feedback

    # ── Streaming / progress ──────────────────────────────────
    events: Annotated[list[AgentEvent], operator.add]
    progress: int                      # 0 – 100
    error: Optional[str]               # Last error message

    # ── Cache ─────────────────────────────────────────────────
    cache_hit: bool                    # True if result served from cache
